Update rust.yml

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -30,30 +30,24 @@ jobs:
         [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
         iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
         choco install git.install --params "'/GitAndUnixToolsOnPath /WindowsTerminal /NoAutoCrlf'" -y --no-progress
+        choco install visualstudio2022buildtools --yes --no-progress
         Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\Git\cmd" -Encoding utf8
         Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\Git\bin" -Encoding utf8
         Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
         refreshenv
         where bash
-    - name: Install and Update winget, then Install Visual Studio Build Tools
+    - name: Verify Visual Studio Build Tools Installation
       shell: pwsh
       run: |
-        # Ensure winget is installed and up-to-date
-        if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
-          Write-Host "winget is not installed. Installing now..."
-          Invoke-WebRequest -Uri https://aka.ms/Microsoft.AppInstaller -OutFile "$env:RUNNER_TEMP\AppInstaller.msi"
-          Start-Process msiexec.exe -ArgumentList "/i", "$env:RUNNER_TEMP\AppInstaller.msi", "/quiet", "/norestart" -Wait
+        $vsWherePath = "$env:ProgramFiles(x86)\Microsoft Visual Studio\Installer\vswhere.exe"
+          
+        if (Test-Path $vsWherePath) {
+          # Run vswhere to verify the installation
+          & $vsWherePath -latest -property installationPath | Out-Null
         } else {
-          Write-Host "winget is already installed."
+          Write-Error "vswhere.exe was not found. Visual Studio Build Tools may not have installed correctly."
+          exit 1
         }
-
-        # Install Visual Studio Build Tools with no confirmation prompts
-        winget install -e --id Microsoft.VisualStudio.2022.BuildTools --accept-source-agreements --accept-package-agreements | Out-Null
-
-    - name: Verify Installation
-      run: |
-        # Check that the Visual Studio Build Tools were installed correctly
-        & "$env:ProgramFiles(x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
     - name: Install Rust (nightly, aarch64)
       if: matrix.os == 'windows-11-preview_aarch64'
       run: |
